### ISSUE TITLE
Uncaught Error: Cannot find module 'invariant'

### ISSUE THREAD

**Issue by luckydonald** [RobCoIndustries/pipboy#16]
It just stays white. Not sure if the error in the console is the reason. (maybe add an status/error display?)
Running this app on a different computer (Mac OS X 10.9.5)
![bildschirmfoto 2015-12-10 um 18 39 35](https://cloud.githubusercontent.com/assets/2737108/11723225/85e54be6-9f6d-11e5-9795-f082ba884388.png)

**Comment by luckydonald** [comment]
The Android app can connect fine, and my Laptop is displaying the game using In-Home Streaming, so that is connected too.

**Comment by luckydonald** [comment]
```
npm install invariant
```

seems to fix that issue.

**Comment by rgbkrk** [comment]
Weird. What version of `npm` and `node` are you on? `invariant` ends up getting installed as part of `history`, a peer dependency of `react-router`.

**Comment by luckydonald** [comment]
```
mac:~ luckydonald$ npm --version
2.14.4
mac:~ luckydonald$ node --version
v4.1.0
```

**Comment by rgbkrk** [comment]
Interesting. I'm on `npm` 3.3.12, which does a flat layout now (as well as some pesky peer deps issues).

**Comment by kitten** [comment]
@rgbkrk Normally peer-dependencies are not installed automatically. That's the difference to normal dependencies. I bet we just forgot to add it to the package.json

**Comment by rgbkrk** [comment]
Ah. That's definitely my fault. It has the appearance of working because of npm 3 installing invariant flatly. I'll fix this now.
