### ISSUE TITLE
Change Color

### ISSUE THREAD

**Issue by luckydonald** [RobCoIndustries/pipboy#17]
It would be great if either
- you can change the color manually
- it uses the same color as set in FO4 on the PC (Like the app does)

**Comment by rgbkrk** [comment]
Wait, does the mobile app reflect what the settings are from the game?

**Comment by luckydonald** [comment]
Yep, mine is yellow. 
So it must dump it somewhere in the data.

**Comment by luckydonald** [comment]
Some uneducated guess:
[DemoMode.json:12874](https://github.com/NimVek/pipboy/blob/1087a1c820fae6265fbce2a614e62e85cd146442/DemoMode.json#L12874)

**Comment by rgbkrk** [comment]
Thanks for digging @luckydonald. Initial implementation in #18. I'll bet @philplckthun has suggestions to make that better later.

**Comment by kitten** [comment]
Not for now :) Looks great!

**Comment by luckydonald** [comment]
Huweee!

**Comment by rgbkrk** [comment]
Now I'll be playing the rest of the game with this blue color.

**Comment by luckydonald** [comment]
I'll be trying to find that place you were.
I just started playing, so that probably will take a while :D

**Comment by rgbkrk** [comment]
Spoiler alert: I am ██ ███ █████████.

**Comment by kitten** [comment]
And also, there you're going to ███  ██  ██.

**Comment by luckydonald** [comment]
I didn't now github has spoiler capabilities. [spoiler]How great[/spoiler].
**Edit:** Huh?

**Comment by rgbkrk** [comment]
:wink: It doesn't. We were playing around using the character "█".

**Comment by kitten** [comment]
...which is Kyle's shameless advertisement for obama :laughing: https://github.com/rgbkrk/obama
