### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by luckydonald** [RobCoIndustries/pipboy#37]
```
The package react@0.14.3 does not satisfy its siblings' peerDependencies requirements!
```

Not sure if i buchered something up here.
If I run `npm install`
![```npm install```](https://cloud.githubusercontent.com/assets/2737108/11870124/31afeaf6-a4c5-11e5-86ef-42f1aeeb6de8.png)
I did `npm install` before, without cleaning/deinstalling anything. Is that the reason?

**Comment by rgbkrk** [comment]
Nuke `node_modules`, run `npm install` again, see what happens.

**Comment by luckydonald** [comment]
Yeah did work.
