### ISSUE TITLE
Update GIF

### ISSUE THREAD

**Issue by rgbkrk** [RobCoIndustries/pipboy#38]
We need an updated GIF in the README.

**Comment by luckydonald** [comment]
Yep.
I always get graphic glitches, but I'll try.

**Comment by rgbkrk** [comment]
[LiceCAP](http://cockos.com/licecap/) is pretty good, though you need to only have one monitor up.

**Comment by luckydonald** [comment]
Have one ready.

**Comment by luckydonald** [comment]
is a 20 MB gif to big?

**Comment by kitten** [comment]
@luckydonald yep

**Comment by luckydonald** [comment]
can github handle a webm instead?
Gif is so an ugly format. Why didn't they choose to make animated PNG an official thing?

**Comment by kitten** [comment]
@luckydonald I don't know. Maybe you should just try? ;) The thing about gif is that it works on every browser. Webm does not (yet)

We can surely compress your gif even further.

Why do you have these strange artifacts on your local map?

**Comment by luckydonald** [comment]
> Why do you have these strange artifacts on your local map?

<del>Lol, you don't?</del>   <br> 
<del>I'd call that a bug?</del><br>
I actually couldn't figure why.

**Comment by luckydonald** [comment]
They do scale.
![screen shot 2015-12-18 at 21 48 26](https://cloud.githubusercontent.com/assets/2737108/11907038/1a54f722-a5d1-11e5-821b-c99820f89fc6.png)

**Comment by kitten** [comment]
@luckydonald Yea, they are definitely sent by your game and not a bug caused by our code

**Comment by luckydonald** [comment]
New gif, 14->8 mb reduced.
![screencapture](https://cloud.githubusercontent.com/assets/2737108/11907104/8dd9d7da-a5d1-11e5-91de-400307f54a53.gif)

**Comment by kitten** [comment]
8 MB is great :)

**Comment by luckydonald** [comment]
The Android app doesn't do that.

**Comment by kitten** [comment]
@luckydonald The in-game local map and the Android app are cropping the local map I think.

**Comment by luckydonald** [comment]
@philplckthun Android screenshot. (Holy Moly thats blurry) 
![img_2015-12-18 21 55 39](https://cloud.githubusercontent.com/assets/2737108/11907165/1ee6a528-a5d2-11e5-80b0-bc5eea2193d7.jpg)
Our App:
![screen shot 2015-12-18 at 21 57 13](https://cloud.githubusercontent.com/assets/2737108/11907206/56e4f4ca-a5d2-11e5-9020-bf815f5f6551.png)

**Comment by kitten** [comment]
@luckydonald (Hut ab! das ging schnell)

Looks cropped to me, but I'm not entirely sure

**Comment by luckydonald** [comment]
@philplckthun 
You are all the time pressing F5 in here, too? Your responses are faster than me writing :D

**Comment by luckydonald** [comment]
Updated in Commit af2b1d7

**Comment by kitten** [comment]
@luckydonald GitHub is actually live-updating its pages

**Comment by luckydonald** [comment]
@philplckthun  should I keep this issue open for next version?
Also: Finally I get to play the game, not only making screenshots. _([ZOCKEN!](http://www.dict.cc/?s=zocken))_

**Comment by kitten** [comment]
CC @rgbkrk 

@luckydonald I'd say no. It's fine. We can probably handle it in another issue the next time or just communicate via Gitter if we need to update it

**Comment by luckydonald** [comment]
@philplckthun  What does CC mean?

**Comment by kitten** [comment]
@luckydonald Just a joke ;) CC as in an Email's carbon copy. We should continue this talk on Gitter to keep this issue uncluttered
